### ISSUE TITLE
Please add a tag when publishing to pub.dartlang.org

### ISSUE THREAD

**Issue by zoechi** [fibulwinter/dart-mockito#12]
```sh
git tag 0.10+1
git push --tags
```
To allow to see what changed from one published version to the next

**Comment by travissanderson-wf** [comment]
seconded

**Comment by travissanderson-wf** [comment]
You should be able to do it retroactively for versions since it was put into git (looks like it was tagged 0.8.0) if the commit that changed the pubspec yaml is the commit that was published: https://github.com/fibulwinter/dart-mockito/commits/master/pubspec.yaml

**Comment by fibulwinter** [comment]
Done
