### ISSUE TITLE
Can't catch errors in when mocking Future.error

### ISSUE THREAD

**Issue by johnpryan** [fibulwinter/dart-mockito#13]
when returning a `Future` in a mock, tests will fail if there is any exception handling using async/await.

```
when(foo.doStuff()).thenReturn(new Future.error('mock error'));
```

In this case, any unit test using async/await and calling `foo.doStuff` will fail with "mock error".  If async/await is not used, the mock error will be caught and the test will pass.

[Heres an example project to help illustrate the problem](https://github.com/johnpryan/mockito_async).  It is using the latest version of [test](https://pub.dartlang.org/packages/test) and mockito.

@fibulwinter @kevmoo

**Comment by kevmoo** [comment]
@nex3 was looking at some issues with how errors are propagated in async code. This might be another case of the same issue.

@johnpryan Would you open an issue? https://github.com/dart-lang/test/issues

**Comment by johnpryan** [comment]
@kevmoo sure.  https://github.com/dart-lang/test/issues/269

**Comment by bunopus** [comment]
Hi, @johnpryan. You could solve your problem just simply use thenAnswer function instead of thenReturn
```dart
when(foo.doStuff()).thenAnswer((_) => new Future.error('mock error'));
```
i`ve created fork of your project with fix https://github.com/bunopus/mockito_async
