### ISSUE TITLE
Ability to mock classes using a 'mock()' function instead of having to define a Mock class

### ISSUE THREAD

**Issue by vikerman** [fibulwinter/dart-mockito#20]
One of the things that's convenient about the Java Mockito library is that there is no need to explicitly define a Mock class. Currently when writing a Dart unit test the developer has to define these mock classes. This usually happens in the test file itself and sometime even duplicated across test files. This increases the friction when writing unit tests.

It would be convenient to just create a mock instance with something like

`Cat mockCat = mock(Cat)`

where mock() is a top-level function of mockito. This makes it similar to the Java library.

The implementation would be a Dart source transformer that parses mock(Type) and generates the Mock class and replaces the mock() call with `new MockCat()` (assuming MockCat is the name of the generated class - might be different in the actual implementation). mock(Type) might itself just be a mockito library function of return type dynamic that just returns null to keep the IDE happy.

Of course there will have to be considerations around warnings/errors to tell the user if they try to pass in anything other than a type that's known at compile time.

Has this been considered before? Please let me know and any comments as I would be interested in implementing this.

**Comment by BlackHC** [comment]
This is not easily possible because you cannot correct proxies with the correct type dynamically :(

**Comment by vikerman** [comment]
I am not suggesting generating the type dynamically during runtime. I am suggesting generating the code that would otherwise be written by hand using a build Transformer, since the pattern seems to be mostly the same. Would that be doable?

**Comment by matanlurey** [comment]
Is mock() with a transformer really that much of a benefit over the 2 lines you need otherwise? Plus all of your tests will now need a transformer to even work.

**Comment by vikerman** [comment]
Would it really add benefit? I guess that's the main question that needs to be answered. My gut feeling was anything that would reduce developer friction while writing unit tests would be useful.

There is also either duplication of mocked classes across test files or extra effort to collect the mocked class in a common place. Not sure how big of a problem that is either.

What sort of data would be helpful in this regard? The average number of mocked classes per unit test file? The average percentage of lines in test that goes towards writing mocks? Instances of mocked class duplications?

Regarding it being a transformer - Adding -mockito to transformers in pubspec.yaml shouldn't be difficult and we should have the default mock() implementation throw an actionable exception message saying you need to add mockito to your transformers in case it's missing. Old tests not using mock() will continue to work without the transformer.

**Comment by TedSander** [comment]
Having less code needs to be carefully balanced with having too much "magic." Magic is great when it works, but when it doesn't it is a cause of a lot of developer angst.

I don't think this savings is worth the added complexity/latency that is added to the build chain. That said if you want to setup a prototype and see how it turns out.

**Comment by Andersmholmgren** [comment]
You can of course always split out mocked classes into helper files so you
can share them between tests.

**Comment by BlackHC** [comment]
I think the proxy issue needs to be solved in general. We're half way
there, and that's always an unfortunate location to be in ^^

**Comment by TedSander** [comment]
Closing this as transformers are no longer recommended by the dart team
