### ISSUE TITLE
Add support for deep stubbing

### ISSUE THREAD

**Issue by BlackHC** [fibulwinter/dart-mockito#21]
It would be nice to have the same that RETURNS_DEEP_STUBS in http://mockito.googlecode.com/svn/tags/1.8.3/javadoc/org/mockito/Mockito.html does.

**Comment by fibulwinter** [comment]
We can't create mock classes on the fly right now - so deep stubbing is impossible until we figure out how to do something like `mock(Class)`.

Also the original mockito feature has this warning:
> This feature should rarely be required for regular clean code! Leave it for legacy code.

Do we really need it?

**Comment by matanlurey** [comment]
I think it's worth closing this :-/, considering it's basically deprecated in Java too.

/cc @TedSander

**Comment by TedSander** [comment]
Agreed
