### ISSUE TITLE
Mock methods

### ISSUE THREAD

**Issue by zijam** [fibulwinter/dart-mockito#23]
I have this example code: 
```
class FooExample {

  int calculate() {
    return myCalc();
  }

  int myCalc() {
    return 6 * 7;
  }
}
```

And I have following test code:
```
import 'package:test/test.dart';
import 'package:mockito/mockito.dart';

class MockFooExample extends Mock implements FooExample { }

void main() {

  FooExample ft = spy(new MockFooExample(), new FooExample());

  test('calculate', () {
    when(ft.myCalc()).thenReturn(10);
    expect(ft.myCalc(), 10);
    expect(ft.calculate(), 10);
  });
}
```

I was expecting the last expect call to return 10, when calling ```ft.calculate()```, but it still return **42**.
Am I missing something?

**Comment by fibulwinter** [comment]
Essentially a spy is a proxy to real object. It would return mock result if you ask for configured it previously, but for anything else it just forward call to real object. Real object has no access to spy, so it will use real methods for all calls.

In your example ft.calculate() will be delegated to real object (as there is no stubbing for it defined) and real object will use real myCalc().

**Comment by zijam** [comment]
Thx for the clarification 👍

**Comment by EasonPai** [comment]
So, without spy how can we do this now?

**Comment by TedSander** [comment]
You can use thenAnswer. It isn't quite as nice, but spy was not going to work without reflection.
final ft = new FooExample();
final mock = new MockFooExample();

  test('calculate', () {
    when(mock.myCalc()).thenReturn(10);
    when(mock.calculate()).thenAnswer(() => ft.calculate());
    expect(mock.myCalc(), 10);
    expect(mock.calculate(), 42);
  });

**Comment by EasonPai** [comment]
Thanks for the help. 

I have thought about thenAnswer, 
but it can be tedious when I have to do partial mocking in a big class.

Do we have any plan to add back `spy` api? or something like `thenCallRealMethod()`
http://static.javadoc.io/org.mockito/mockito-core/2.15.0/org/mockito/Mockito.html#partial_mocks

**Comment by TedSander** [comment]
Sorry no. Spy used mirrors which can't be used in dart AOT environments such as flutter and soon web. https://github.com/dart-lang/mockito/issues/27

I don't believe this will be possible using our current implementation. It would require a complete rewrite of mockito using codegen which isn't happening anytime soon, and the migration may have other downsides such as slower build/dev cycle times.

For what it's worth in our corpus of code (millions of lines of code) we aren't missing it. It was only used in a couple of places and was easy to migrate.

**Comment by kjawadDeveloper1** [comment]
Any update on using Spy methods?

**Comment by srawlins** [comment]
No; no current plans for supporting spies.

**Comment by kjawadDeveloper** [comment]
@srawlins how we can do such testing?
