### ISSUE TITLE
Allow `any` to work with Strong mode

### ISSUE THREAD

**Issue by srawlins** [fibulwinter/dart-mockito#25]
This is a sibling issue to https://github.com/dart-lang/sdk/issues/26036.

The issue is that we cannot use `any` with Strong mode turned on. For example:

```dart
int f(List<int> l) => l[0];

void main() {
  f(any);
}
```

Yields an analyzer error (`dartanalyzer --strong a.dart`): "Unsound implicit cast from dynamic to List<int>".

I think we can solve this on the Mockito side, similar to Java Mockito's [`any()`](http://site.mockito.org/mockito/docs/current/org/mockito/Matchers.html#any()).

I have a prototype implementation that uses the Strong mode type parameter comments:

```dart
/*=T*/ any/*<T>*/([/*=T*/ e = null]) => null;
```

The tricky part is that `any` would now return `null`, instead of the `_ArgMatcher` (again similar to [Java Mockito's](https://github.com/mockito/mockito/blob/master/src/main/java/org/mockito/Matchers.java#L161..L163), and we would have to implement something like Java Mockito's [reportMatcher()](https://github.com/mockito/mockito/blob/master/src/main/java/org/mockito/AdditionalMatchers.java#L989..L991), maybe changing how the whole matching situation works...

What do you think? Any thoughts or other ideas?

**Comment by leafpetersen** [comment]
@kevmoo Any thoughts on this?
