### ISSUE TITLE
Mockito without mirrors?

### ISSUE THREAD

**Issue by Hixie** [fibulwinter/dart-mockito#27]
Would it be possible to create a version of mockito that doesn't use dart:mirrors? That would enable mockito to be used in environments that disable the mirrors support.

**Comment by matanlurey** [comment]
It looks like the only invocation of true mirrors is `spy`:

```dart
dynamic spy(dynamic mock, dynamic spiedObject) {
  var mirror = reflect(spiedObject);
  mock._defaultResponse = () => new CannedResponse(
      null, (Invocation realInvocation) => mirror.delegate(realInvocation));
  return mock;
}
```

I imagine this could be moved to mockito/spy.dart.

The rest of mirrors uses `noSuchMethod`, which is a sort of mirrors-light. Is that still supported in Flutter/AOT? We've had a few conversations about code-gen based mockito that had mixed reviews.

**Comment by matanlurey** [comment]
It looks like `noSuchMethod` works for AOT. @TedSander is this a reasonable change?

**Comment by TedSander** [comment]
Yep seems reasonable. Anyone want to send a pull request? I imagine we shouldn't have a breaking change for this. So have the original entrypoint export spy.dart, and mock.dart (or something like that,) and have AOT just import the second one.

**Comment by matanlurey** [comment]
@Hixie does that sound OK? 

We'd have:

```
lib/
  src/
    mock.dart
    spy.dart
  mockito.dart: Original library that also exports spy (won't work in AOT)
  mockito_no_mirrors.dart: Mockito without the spy function (or whatever else is added)
```

**Comment by Hixie** [comment]
sgtm

**Comment by Hixie** [comment]
and thanks for looking at this so quickly! much appreciated.

**Comment by matanlurey** [comment]
@TedSander I'll shoot you a PR shortly :kiss:

**Comment by matanlurey** [comment]
@Hixie of course!

**Comment by matanlurey** [comment]
Alright, take a look:

https://github.com/fibulwinter/dart-mockito/pull/28

**Comment by Hixie** [comment]
Thanks!
