### ISSUE TITLE
More Maintainers

### ISSUE THREAD

**Issue by TedSander** [fibulwinter/dart-mockito#4]
I'm not sure how to give you this message otherwise, but I would be happy to help you maintain this if you are looking for someone to help.

**Comment by fibulwinter** [comment]
I've added you to collaborators.

**Comment by pq** [comment]
If you want more hands, I'd be up for pitching in too.

Cheers!

**Comment by fibulwinter** [comment]
I've added you to collaborators as well.

**Comment by pq** [comment]
Super.  Thanks!
