### ISSUE TITLE
spy constructor

### ISSUE THREAD

**Issue by cgarciae** [fibulwinter/dart-mockito#6]
Like the `mock` library.

**Comment by fibulwinter** [comment]
Can you provide an example of use case?

**Comment by cgarciae** [comment]
Sometime mocking things like a database driver or a graph-like structure are hard to mock because of their structural or functional complexity, you might instead prefer to use an implementation but still be able to log the objects activity.

##### Use case 
**Some script**
```dart
foo (db) => db.find (...).filter.(...).map(...);
```
To get right, in `find` you have to tell the `mock` to return an object that has a `filter` method, that returns a object that has a `map` methods. Since nested structures take more effort, it might be easier to use a spy a.

**Comment by fibulwinter** [comment]
Done in 0.10.0
```dart
  //spy creation
  var cat = spy(new MockCat(), new Cat());
  //stubbing - before execution
  when(cat.sound()).thenReturn("Purr");
  //using mocked interaction
  expect(cat.sound(), "Purr");  
  //using real object
  expect(cat.lives, 9);   
```

**Comment by cgarciae** [comment]
Excellent!
